# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170404_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.IntegerField(null=True, verbose_name='Ticket'),
        ),
    ]
